apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: weather-check
        image: 1nfosecsingh/demo-app:v2025010506342220250105063128
        ports:
        - containerPort: 5000
