name: Test and Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setting up Environment  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

    
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

        # Testing my Code   

      - name: Run linting tests
        run: |
          flake8 . --exclude=venv

      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
         
      - name: Docker tag
        id: version
        run: |
              VERSION=v$(date+"%Y%m%d%H%M%S") 
              echo "VERSION=$VERSION >> $GITHUB_ENV"


          # Build the Docker Image

      - name: Build Docker Image
        run: |
          docker build . -t fahadmalik1/demo-app: ${{env.VERSION}}

        # Push the Docker Image








        